apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: civicpulse

resources:
  - ../../base

images:
  - name: ghcr.io/minah-bot/civicpulse-backend
    newTag: REPLACE_WITH_SHA
  - name: ghcr.io/minah-bot/civicpulse-frontend
    newTag: REPLACE_WITH_SHA

patches:
  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "750m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"
