apiVersion: apps/v1
kind: Deployment
metadata:
  name: civicpulse-frontend
  labels:
    app: civicpulse-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: civicpulse-frontend
  template:
    metadata:
      labels:
        app: civicpulse-frontend
    spec:
      containers:
        - name: frontend
          image: civicpulse-frontend:dev-placeholder
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi

